version: '3.8'

services:
  db:
    image: postgres:13
    container_name: api-gateway-db
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    ports:
      - "49152:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  cache:
    image: redis:latest
    container_name: api-gateway-redis
    networks:
      - kong-net
    volumes:
      - ./tmp/cache:/var/lib/postgresql/data

  app:
    image: kong:latest
    container_name: api-gateway
    networks:
      - kong-net
    depends_on:
      - db
      - cache
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: api-gateway-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"

networks:
  kong-net:
    driver: bridge
